// api_post_export.js
//
// Handles exporting a generated vibes.fm playlist to Spotify.
// This runs server-side to avoid browser CORS restrictions.
//

exports.post_export = async (request, response) => {

    try {
        let access_token = request.body.access_token;
        let vibe_name = request.body.vibe_name;
        let track_ids = request.body.track_ids; // array of Spotify track IDs

        if (!access_token || !vibe_name || !track_ids || track_ids.length === 0) {
            return response.status(400).json({ message: "Missing required fields" });
        }

        console.log("**Call to post /export...");
        console.log(`Creating playlist "${vibe_name}" with ${track_ids.length} tracks`);

        // 1. Get current user
        let meRes = await fetch('https://api.spotify.com/v1/me', {
            headers: { 'Authorization': `Bearer ${access_token}` }
        });
        if (!meRes.ok) {
            let err = await meRes.text();
            console.log("Spotify /me error:", meRes.status, err);
            return response.status(meRes.status).json({ message: "Spotify auth failed: " + err });
        }
        let userData = await meRes.json();
        console.log("Authenticated as:", userData.id);

        // 2. Create playlist using /me/playlists (works more reliably)
        let createRes = await fetch('https://api.spotify.com/v1/me/playlists', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${access_token}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                name: vibe_name,
                description: 'Generated by vibes.fm',
                public: false
            })
        });
        if (!createRes.ok) {
            let err = await createRes.text();
            console.log("Spotify create playlist error:", createRes.status, err);
            return response.status(createRes.status).json({ message: "Failed to create playlist: " + err });
        }
        let playlistData = await createRes.json();
        console.log("Created playlist:", playlistData.id);

        // 3. Add tracks in batches of 100
        let trackUris = track_ids.map(id => `spotify:track:${id}`);
        console.log("Total track URIs:", trackUris.length);
        console.log("First 3 URIs:", trackUris.slice(0, 3));
        
        // Try adding just 1 track first to debug
        console.log("Attempting to add first track only:", trackUris[0]);
        let testRes = await fetch(`https://api.spotify.com/v1/playlists/${playlistData.id}/items`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${access_token}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ uris: [trackUris[0]] })
        });
        console.log("Single track add result:", testRes.status);
        if (!testRes.ok) {
            let err = await testRes.text();
            console.log("Single track add error body:", err);
            
            // If single track fails too, try the query parameter approach
            console.log("Trying query parameter approach...");
            let queryRes = await fetch(
                `https://api.spotify.com/v1/playlists/${playlistData.id}/items?uris=${encodeURIComponent(trackUris[0])}`,
                {
                    method: 'POST',
                    headers: { 'Authorization': `Bearer ${access_token}` }
                }
            );
            console.log("Query param approach result:", queryRes.status);
            if (!queryRes.ok) {
                let qErr = await queryRes.text();
                console.log("Query param error:", qErr);
                return response.status(queryRes.status).json({ message: "Failed to add tracks: " + qErr });
            }
        }
        
        // If we got here with the single track approach, add the rest
        if (trackUris.length > 1) {
            let remaining = trackUris.slice(1);
            for (let i = 0; i < remaining.length; i += 100) {
                let batch = remaining.slice(i, i + 100);
                console.log(`Adding batch, ${batch.length} tracks...`);
                
                let addRes = await fetch(`https://api.spotify.com/v1/playlists/${playlistData.id}/items`, {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${access_token}`,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ uris: batch })
                });
                if (!addRes.ok) {
                    let err = await addRes.text();
                    console.log("Batch add tracks error:", addRes.status, err);
                    return response.status(addRes.status).json({ message: "Failed to add tracks: " + err });
                }
            }
        }

        console.log("Export complete!");
        response.json({
            message: "success",
            playlist_id: playlistData.id,
            playlist_url: playlistData.external_urls?.spotify || ""
        });

    } catch (err) {
        console.log("ERROR in export:", err.message);
        response.status(500).json({ message: err.message });
    }
};
